swagger: "2.0"
info:
  title: "API de Empleados"
  description: "API para gestionar empleados"
  version: "1.0.0"
basePath: "/api/empleados"
schemes:
  - "http"
paths:
  /:
    get:
      summary: "Obtener todos los empleados"
      description: "Devuelve una lista de todos los empleados."
      responses:
        200:
          description: "Lista de empleados obtenida exitosamente"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Empleado"
    post:
      summary: "Crear un nuevo empleado"
      description: "Crea un nuevo empleado."
      parameters:
        - name: "Empleado"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/EmpleadoInput"
      responses:
        201:
          description: "Empleado creado exitosamente"
          schema:
            $ref: "#/definitions/Empleado"
  /{id}:
    parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
    get:
      summary: "Obtener un empleado por ID"
      description: "Devuelve un empleado por su ID."
      responses:
        200:
          description: "Empleado obtenido exitosamente"
          schema:
            $ref: "#/definitions/Empleado"
        404:
          description: "Empleado no encontrado"
    put:
      summary: "Actualizar un empleado por ID"
      description: "Actualiza un empleado existente por su ID."
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
        - name: "Empleado"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/EmpleadoInput"
      responses:
        200:
          description: "Empleado actualizado exitosamente"
          schema:
            $ref: "#/definitions/Empleado"
        404:
          description: "Empleado no encontrado"
    delete:
      summary: "Eliminar un empleado por ID"
      description: "Elimina un empleado por su ID."
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        204:
          description: "Empleado eliminado exitosamente"
        404:
          description: "Empleado no encontrado"
definitions:
  Empleado:
    type: "object"
    properties:
      _id:
        type: "string"
      nombre:
        type: "string"
      cargo:
        type: "string"
      salario:
        type: "number"
  EmpleadoInput:
    type: "object"
    properties:
      nombre:
        type: "string"
      cargo:
        type: "string"
      salario:
        type: "number"
